### ISSUE TITLE
Integrity test of ETL images does not fail on missing labels

### ISSUE THREAD

**Issue by zstadler** [openmaptiles/openmaptiles#1221]
The [integrity test for #1202](https://github.com/openmaptiles/openmaptiles/pull/1202/checks#step:5:11)  said:

```
Warning: node layer_mountain_peak, port z13_ unrecognized
```

This is an indication of a bug in the ETL definitions that should have been be detected by the integrity test and require the PR fix it.

**Comment by zstadler** [comment]
Related to https://github.com/openmaptiles/openmaptiles/pull/1187/files#r706607987
and https://github.com/openmaptiles/openmaptiles/pull/1202/files#r706606340

**Comment by Falke-Design** [comment]
@nyurik fixed with #1223

**Comment by nyurik** [comment]
@Falke-Design i think #1221 only fixes the actual bug with ETL declaration. We still don't have ETL integration tests. These tests should fail if ETL is incorrect **before** we merge them.

**Comment by ZeLonewolf** [comment]
I agree, I fixed the bug, but the bug should have caused a test failure, which is what this issue is about.
