### ISSUE TITLE
Missing labels for oceans and seas

### ISSUE THREAD

**Issue by ZeLonewolf** [openmaptiles/openmaptiles#1468]
`water_name` point labels are missing for the following cases:
* `name=` is empty (but other `name:xx` tags exists), for example, [Atlantic Ocean](https://www.openstreetmap.org/node/305640306)
* The ocean or sea is mapped as an area, for example, [Gulf of Mexico](https://www.openstreetmap.org/way/808726001)

As a result, obvious ocean/sea labels that should be present are missing:

![image](https://user-images.githubusercontent.com/3254090/210123431-23ab3df2-465f-4253-8ddb-e68b4a2bb8bb.png)

**Comment by ZeLonewolf** [comment]
The missing Atlantic Ocean labels are probably due to a user that added `noname=yes` to the nodes.  This has been fixed in https://www.openstreetmap.org/changeset/130716077.

**Comment by mmc1718** [comment]
@ZeLonewolf I believe Atlantic ocean name labels are still missing - was there ever a fix for the first case mentioned here - `name` tag missing but language specific name tags are available? 

I understand there is a debate on how to tag the Atlantic Ocean nodes, I don't really understand the details (just discovering it here https://community.openstreetmap.org/t/atlantic-ocean-repeated-name-removal/101196) but am I right in thinking these three labels are missing now because of the inconsistency in tagging compared to other oceans e.g. Pacific? If so, can this issue be reopened?
