### ISSUE TITLE
Insufficient level of detail on  zoom level 7

### ISSUE THREAD

**Issue by juho-hanhimaki** [openmaptiles/openmaptiles#210]
We're having issues with too low amount of detail in some zoom levels. For example the OSM2VT used to provide a lot more detail in similar zoom levels. Also comparing to other map providers such as Google, openmaptiles is missing huge amounts of detail on similar zoom levels.

Please see this screenshot of southern Finland (main part of Finland). One can't really see much useful data on this map compared to OSM2VT which had nice amount of detail.

![openmaptiles](https://cloud.githubusercontent.com/assets/12390182/24806365/47b8c708-1bbd-11e7-8bd8-f9200c0614a0.png)

As far as i know this isn't issue with styles, it's just how the data is. For us this is problematic as we need to show asset locations on map and there needs to be enough visible context/detail for the user.

**Comment by pathmapper** [comment]
Apart from the question what details for which zoom level should be displayed by default, you have the possibility to modify the layer SQL code to fit your needs.

Example:
To have more detailed lakes on lower zoom levels you could adapt [water.sql](https://github.com/openmaptiles/openmaptiles/blob/master/layers/water/water.sql).
Take a look at the [schema](https://openmaptiles.org/schema/#water) and the diagrams to find out which sources are used for which zoom level by default.

**Comment by klokan** [comment]
Zoom level 7 should be improved indeed - roads are tracked under #200 already, more of the place names should be elevated from zoom 8 here too. Pull requests from the community are very welcome - @stirringhalo - are you going to have time for this one?

We have to be very careful about the size of the final tiles and number of edges - an aggressive merging and generalization of the elevated features is required.

**Comment by stirringhalo** [comment]
@klokan Hope so, definitely before v3.6.

**Comment by stirringhalo** [comment]
This is indeed fixed with #214

**Comment by stirringhalo** [comment]
Closed with #214

**Comment by juho-hanhimaki** [comment]
I tried generating tiles with the new version and unfortunately it seems the problem still exists for us. The roads are certainly better now but the insufficient detail of place names are quite terrible for us. Even though Finland is a country of little population I don't think the map should look like empty canvas.

Please compare this image of 3.6 version to the image in original message:
![openmaptiles36](https://user-images.githubusercontent.com/12390182/27121014-50a5328c-50ee-11e7-898f-f3d7ede132c1.png)

**Comment by stirringhalo** [comment]
Definitely worth improving, I would love to do something where layers are shown much earlier, and simply filtered by details. Should be done for 3.7

**Comment by jirik** [comment]
@stirringhalo That would be great. We can show landcover/landuse at zoom level 7 and we can also show more places at this level.

**Comment by stirringhalo** [comment]
Playing with landcover and city names showing up at z7 in https://github.com/openmaptiles/openmaptiles/pull/283

**Comment by stirringhalo** [comment]
How it is now:

![image](https://user-images.githubusercontent.com/14035518/27265448-37cc3fd4-5464-11e7-9c08-8c2e7a4c10bf.png)

P.S., still lots of tuning to do with ZRes.

**Comment by juho-hanhimaki** [comment]
Sorry for resurrecting old thread, but I feel the level of detail at this zoom level is still problematic in some areas.

It seems the regular OpenStreetMap is also struggling here.

Please compare in smallish browser window (for example 1200x700ish, tablet size).

https://openmaptiles.github.io/klokantech-basic-gl-style/#7/61.794/27.416
https://www.openstreetmap.org/#map=8/61.794/27.416

compare to
https://www.google.com/maps/@61.794,27.416,8z

Now the OSM based solutions seem very poor in detail compared to the google maps. There is very little context visible in the OSM.

I realize google has totally different data/technology.

Still, this seems like something that could be improved. And i feel its quite important because many applications would work better with more context. Would it be possible for OpenMapTiles to do some black magic with the OSM data to exceed the quality of standard OSM?

**Comment by klokan** [comment]
This is how to window look in OSM Bright in the latest release v3.7:

https://openmaptiles.github.io/osm-bright-gl-style/#7.02/61.829/27.416

![screen shot 2017-12-13 at 11 37 23](https://user-images.githubusercontent.com/59284/33934791-36b81394-dffa-11e7-9c37-46ef6224219e.png)

You can speak to OpenStreetMap Finland and get involved in the improvement of the geo data - it seems some of the place names could be tagged differently for improved visibility as in other countries.

Our team is available for hire to make additional improvements on OpenMapTiles: https://openmaptiles.com/support/

If you believe further improvements are required, please make a new ticket.

This ticket is closed. Nothing more will happen here.

**Comment by juho-hanhimaki** [comment]
I didn't realize there was such huge difference made by style here. OSM bright indeed is much better in the amount of detail.

Thanks.

**Comment by klokan** [comment]
Even better is our new KlokanTech Street premium style - made for https://www.tilehosting.com/
