### ISSUE TITLE
housenumber and POI overlap

### ISSUE THREAD

**Issue by golubev** [openmaptiles/openmaptiles#798]
Hello :wave:

We ran into an issue with housenumbers and POIs at our OMT maps. It is critical for us to show both the housenumbers and the POIs.

It seems that POIs and housenumbers pretty often share the same coordinates and they fight for being displayed on the map as they overlap. We tried to use `text-offset` and `text-allow-overlap` mapbox style properties but that didn't seem to look nice, especially on small buildings.

Have anybody faced the same issue? Perhaps, somebody can give an advice for a workaround or a solid fix. Thanks in advance :hand: 

I noticed that they both are being placed into buildings polygons centroids. I think that this is causing them to overlap:

https://github.com/openmaptiles/openmaptiles/blob/8fe9af23279067201450ec1e06dbb33e296ce085/layers/housenumber/housenumber_centroid.sql#L7-L13

https://github.com/openmaptiles/openmaptiles/blob/ff99a02aae287ed0546abe705c981e71c8618c33/layers/poi/update_poi_polygon.sql#L8-L14

**Comment by eva-j** [comment]
Related to https://github.com/openmaptiles/openmaptiles/issues/766

**Comment by daliborjanak** [comment]
Duplicate to #766

**Comment by golubev** [comment]
If https://github.com/openmaptiles/openmaptiles/issues/766 is resolved - will we see on a map both a POI and a house number (without overlapping) for a house that has a corresponding feature in `osm_poi_polygon`?

Now for such houses OMT places both the POI and the house number in a centroid and they overlap.

**Comment by eva-j** [comment]
@golubev You are right, for polygon POIs it is not resolved. For me this is style issue, I don't think there can be found a good solution on data side.

**Comment by golubev** [comment]
I think that this can be resolved on the data side as well.

As well as we can play with offsets in style we may start placing houses numbers and polygon-POIs in different points by giving them different coordinates. But that would be quite tricky to implement for the non-convex polygons )
